-- TeamBox: messaggi diretti e allegati reali.
-- Esegui questo file UNA VOLTA nel SQL Editor di Supabase, dopo supabase_repair.sql.

create table if not exists public.direct_threads (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now()
);

create table if not exists public.direct_thread_members (
  thread_id bigint not null references public.direct_threads(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (thread_id, profile_id)
);

create table if not exists public.direct_messages (
  id bigint generated by default as identity primary key,
  thread_id bigint not null references public.direct_threads(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 4000),
  created_at timestamptz not null default now()
);

create index if not exists direct_messages_thread_created_at_idx on public.direct_messages(thread_id, created_at);

create table if not exists public.message_attachments (
  id bigint generated by default as identity primary key,
  message_id bigint not null references public.messages(id) on delete cascade,
  file_name text not null check (char_length(file_name) between 1 and 255),
  file_path text not null unique,
  mime_type text,
  byte_size bigint not null check (byte_size >= 0),
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table public.direct_threads enable row level security;
alter table public.direct_thread_members enable row level security;
alter table public.direct_messages enable row level security;
alter table public.message_attachments enable row level security;

create or replace function public.is_direct_thread_member(target_thread_id bigint)
returns boolean language sql security definer stable set search_path = public as $$
  select exists (
    select 1 from public.direct_thread_members
    where thread_id = target_thread_id and profile_id = auth.uid()
  );
$$;

create or replace function public.get_or_create_direct_thread(other_profile_id uuid)
returns bigint language plpgsql security definer set search_path = public as $$
declare
  existing_thread_id bigint;
  new_thread_id bigint;
begin
  if auth.uid() is null then raise exception 'Devi accedere prima di avviare una chat diretta.'; end if;
  if other_profile_id = auth.uid() then raise exception 'Non puoi aprire una chat diretta con te stessa/o.'; end if;

  select mine.thread_id into existing_thread_id
  from public.direct_thread_members mine
  join public.direct_thread_members other on other.thread_id = mine.thread_id
  where mine.profile_id = auth.uid() and other.profile_id = other_profile_id
  limit 1;
  if existing_thread_id is not null then return existing_thread_id; end if;

  insert into public.direct_threads default values returning id into new_thread_id;
  insert into public.direct_thread_members (thread_id, profile_id)
  values (new_thread_id, auth.uid()), (new_thread_id, other_profile_id);
  return new_thread_id;
end;
$$;

drop policy if exists "Members read direct threads" on public.direct_threads;
drop policy if exists "Members read direct thread members" on public.direct_thread_members;
drop policy if exists "Members read direct messages" on public.direct_messages;
drop policy if exists "Members send direct messages" on public.direct_messages;
drop policy if exists "Team members read attachments" on public.message_attachments;
drop policy if exists "Members create their attachments" on public.message_attachments;
drop policy if exists "Members delete their attachments" on public.message_attachments;

create policy "Members read direct threads" on public.direct_threads for select to authenticated using (public.is_direct_thread_member(id));
create policy "Members read direct thread members" on public.direct_thread_members for select to authenticated using (public.is_direct_thread_member(thread_id));
create policy "Members read direct messages" on public.direct_messages for select to authenticated using (public.is_direct_thread_member(thread_id));
create policy "Members send direct messages" on public.direct_messages for insert to authenticated with check (author_id = auth.uid() and public.is_direct_thread_member(thread_id));
create policy "Team members read attachments" on public.message_attachments for select to authenticated using (true);
create policy "Members create their attachments" on public.message_attachments for insert to authenticated with check (created_by = auth.uid());
create policy "Members delete their attachments" on public.message_attachments for delete to authenticated using (created_by = auth.uid());

revoke all on function public.is_direct_thread_member(bigint) from public;
grant execute on function public.is_direct_thread_member(bigint) to authenticated;
revoke all on function public.get_or_create_direct_thread(uuid) from public;
grant execute on function public.get_or_create_direct_thread(uuid) to authenticated;

insert into storage.buckets (id, name, public, file_size_limit)
values ('teambox-files', 'teambox-files', false, 26214400)
on conflict (id) do update set public = false, file_size_limit = 26214400;

drop policy if exists "TeamBox members read files" on storage.objects;
drop policy if exists "TeamBox members upload files" on storage.objects;
drop policy if exists "TeamBox members delete their files" on storage.objects;
create policy "TeamBox members read files" on storage.objects for select to authenticated using (bucket_id = 'teambox-files');
create policy "TeamBox members upload files" on storage.objects for insert to authenticated with check (bucket_id = 'teambox-files');
-- Alcuni progetti Supabase creati con una versione precedente hanno owner_id come text;
-- il confronto testuale funziona anche nei progetti più recenti, dove è un uuid.
create policy "TeamBox members delete their files" on storage.objects for delete to authenticated using (bucket_id = 'teambox-files' and owner_id::text = auth.uid()::text);

do $$
begin
  alter publication supabase_realtime add table public.direct_messages;
exception when duplicate_object then null;
end;
$$;

-- Canali con membri scelti dal creatore.
create table if not exists public.channel_members (
  channel_id bigint not null references public.channels(id) on delete cascade,
  profile_id uuid not null references public.profiles(id) on delete cascade,
  added_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now(),
  primary key (channel_id, profile_id)
);

-- Ogni nuovo membro vede subito il canale generale; gli altri canali restano
-- selezionabili dal loro creatore nella finestra "People in channel".
create or replace function public.create_profile_for_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name, avatar_color)
  values (new.id, coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(new.email, '@', 1)), 'violet')
  on conflict (id) do nothing;

  insert into public.channel_members (channel_id, profile_id, added_by)
  select channel.id, new.id, null
  from public.channels channel
  where lower(channel.slug) in ('general', 'generale')
  on conflict do nothing;
  return new;
end;
$$;

alter table public.channel_members enable row level security;

create or replace function public.is_channel_member(target_channel_id bigint)
returns boolean language sql security definer stable set search_path = public as $$
  select exists (
    select 1 from public.channel_members
    where channel_id = target_channel_id and profile_id = auth.uid()
  );
$$;

create or replace function public.is_channel_owner(target_channel_id bigint)
returns boolean language sql security definer stable set search_path = public as $$
  select exists (
    select 1 from public.channels
    where id = target_channel_id and created_by::text = auth.uid()::text
  );
$$;

create or replace function public.create_team_channel(
  channel_slug text,
  channel_description text,
  invited_profile_ids uuid[] default array[]::uuid[]
)
returns table (id bigint, slug text, description text, created_at timestamptz)
language plpgsql security definer set search_path = public as $$
declare
  new_channel_id bigint;
begin
  if auth.uid() is null then raise exception 'Devi accedere prima di creare un canale.'; end if;
  if channel_slug !~ '^[a-z0-9-]{1,48}$' then raise exception 'Nome del canale non valido.'; end if;

  insert into public.channels (slug, description, created_by)
  values (channel_slug, coalesce(nullif(channel_description, ''), 'Un nuovo spazio per il team'), auth.uid())
  returning channels.id into new_channel_id;

  insert into public.channel_members (channel_id, profile_id, added_by)
  values (new_channel_id, auth.uid(), auth.uid())
  on conflict do nothing;

  insert into public.channel_members (channel_id, profile_id, added_by)
  select new_channel_id, profile.id, auth.uid()
  from public.profiles profile
  where profile.id = any(coalesce(invited_profile_ids, array[]::uuid[]))
  on conflict do nothing;

  return query select channels.id, channels.slug, channels.description, channels.created_at
  from public.channels where channels.id = new_channel_id;
end;
$$;

create or replace function public.add_channel_members(
  target_channel_id bigint,
  invited_profile_ids uuid[]
)
returns void language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null or not public.is_channel_owner(target_channel_id) then
    raise exception 'Solo chi ha creato il canale può aggiungere persone.';
  end if;
  insert into public.channel_members (channel_id, profile_id, added_by)
  select target_channel_id, profile.id, auth.uid()
  from public.profiles profile
  where profile.id = any(coalesce(invited_profile_ids, array[]::uuid[]))
  on conflict do nothing;
end;
$$;

-- Mantiene utilizzabili i canali già creati aggiungendo gli attuali membri del workspace.
insert into public.channel_members (channel_id, profile_id, added_by)
select
  channel.id,
  profile.id,
  case when channel.created_by::text = profile.id::text then profile.id else null end
from public.channels channel cross join public.profiles profile
on conflict do nothing;

drop policy if exists "Team members can read channels" on public.channels;
drop policy if exists "Team members can create channels" on public.channels;
drop policy if exists "Team members can read messages" on public.messages;
drop policy if exists "Team members can send messages" on public.messages;
drop policy if exists "Channel members can read memberships" on public.channel_members;
drop policy if exists "Channel members can read channels" on public.channels;
drop policy if exists "Channel members can read messages" on public.messages;
drop policy if exists "Channel members can send messages" on public.messages;

create policy "Channel members can read memberships" on public.channel_members for select to authenticated using (public.is_channel_member(channel_id));
create policy "Channel members can read channels" on public.channels for select to authenticated using (public.is_channel_member(id));
create policy "Channel members can read messages" on public.messages for select to authenticated using (public.is_channel_member(channel_id));
create policy "Channel members can send messages" on public.messages for insert to authenticated with check (author_id::text = auth.uid()::text and public.is_channel_member(channel_id));

revoke all on function public.is_channel_member(bigint) from public;
grant execute on function public.is_channel_member(bigint) to authenticated;
revoke all on function public.is_channel_owner(bigint) from public;
grant execute on function public.is_channel_owner(bigint) to authenticated;
revoke all on function public.create_team_channel(text, text, uuid[]) from public;
grant execute on function public.create_team_channel(text, text, uuid[]) to authenticated;
revoke all on function public.add_channel_members(bigint, uuid[]) from public;
grant execute on function public.add_channel_members(bigint, uuid[]) to authenticated;

-- Un canvas condiviso e privato per ciascuna chat diretta 1:1.
create table if not exists public.direct_canvases (
  thread_id bigint primary key references public.direct_threads(id) on delete cascade,
  title text not null default 'Appunti condivisi' check (char_length(title) between 1 and 100),
  content jsonb not null default '{"notes":"","tables":[]}'::jsonb,
  updated_by uuid not null references public.profiles(id) on delete cascade,
  updated_at timestamptz not null default now()
);

alter table public.direct_canvases enable row level security;
drop policy if exists "Direct members read canvas" on public.direct_canvases;
drop policy if exists "Direct members create canvas" on public.direct_canvases;
drop policy if exists "Direct members update canvas" on public.direct_canvases;
create policy "Direct members read canvas" on public.direct_canvases for select to authenticated using (public.is_direct_thread_member(thread_id));
create policy "Direct members create canvas" on public.direct_canvases for insert to authenticated with check (updated_by = auth.uid() and public.is_direct_thread_member(thread_id));
create policy "Direct members update canvas" on public.direct_canvases for update to authenticated using (public.is_direct_thread_member(thread_id)) with check (updated_by = auth.uid() and public.is_direct_thread_member(thread_id));

do $$
begin
  alter publication supabase_realtime add table public.direct_canvases;
exception when duplicate_object then null;
end;
$$;

-- Shared AUREA calendar: events and scheduled video calls.
create table if not exists public.calendar_events (
  id bigint generated by default as identity primary key,
  title text not null check (char_length(title) between 1 and 120),
  starts_at timestamptz not null,
  ends_at timestamptz not null check (ends_at > starts_at),
  kind text not null default 'event' check (kind in ('event', 'call')),
  channel_id bigint references public.channels(id) on delete set null,
  video_room text,
  created_by uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists calendar_events_starts_at_idx on public.calendar_events(starts_at);
alter table public.calendar_events enable row level security;
drop policy if exists "Team members read calendar events" on public.calendar_events;
drop policy if exists "Members create calendar events" on public.calendar_events;
drop policy if exists "Members update their calendar events" on public.calendar_events;
drop policy if exists "Members delete their calendar events" on public.calendar_events;
create policy "Team members read calendar events" on public.calendar_events for select to authenticated using (true);
create policy "Members create calendar events" on public.calendar_events for insert to authenticated with check (created_by = auth.uid());
create policy "Members update their calendar events" on public.calendar_events for update to authenticated using (created_by = auth.uid()) with check (created_by = auth.uid());
create policy "Members delete their calendar events" on public.calendar_events for delete to authenticated using (created_by = auth.uid());

do $$
begin
  alter publication supabase_realtime add table public.calendar_events;
exception when duplicate_object then null;
end;
$$;
