-- TeamBox: database, autenticazione e regole di sicurezza.
create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 1 and 40),
  avatar_color text not null default 'violet' check (avatar_color in ('coral','blue','gold','violet')),
  created_at timestamptz not null default now()
);

create table public.channels (
  id bigint generated by default as identity primary key,
  slug text not null unique check (slug ~ '^[a-z0-9-]{1,48}$'),
  description text not null default '',
  created_by uuid references public.profiles(id) on delete set null,
  created_at timestamptz not null default now()
);

create table public.messages (
  id bigint generated by default as identity primary key,
  channel_id bigint not null references public.channels(id) on delete cascade,
  author_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) between 1 and 4000),
  created_at timestamptz not null default now()
);

create index messages_channel_created_at_idx on public.messages(channel_id, created_at);

alter table public.profiles enable row level security;
alter table public.channels enable row level security;
alter table public.messages enable row level security;

create policy "Team members can read profiles" on public.profiles for select to authenticated using (true);
create policy "Members create their own profile" on public.profiles for insert to authenticated with check ((select auth.uid()) = id);
create policy "Members update their own profile" on public.profiles for update to authenticated using ((select auth.uid()) = id) with check ((select auth.uid()) = id);
create policy "Team members can read channels" on public.channels for select to authenticated using (true);
create policy "Team members can create channels" on public.channels for insert to authenticated with check ((select auth.uid()) = created_by);
create policy "Team members can read messages" on public.messages for select to authenticated using (true);
create policy "Team members can send messages" on public.messages for insert to authenticated with check ((select auth.uid()) = author_id);

create or replace function public.create_profile_for_new_user()
returns trigger language plpgsql security definer set search_path = public as $$
begin
  insert into public.profiles (id, display_name, avatar_color)
  values (new.id, coalesce(nullif(new.raw_user_meta_data ->> 'display_name', ''), split_part(new.email, '@', 1)), 'violet');
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.create_profile_for_new_user();

insert into public.channels (slug, description) values
  ('generale', 'Comunicazioni e aggiornamenti per tutto il team'),
  ('progetto', 'Tutto quello che riguarda il progetto in corso'),
  ('design', 'Idee, feedback e risorse per il design');

alter publication supabase_realtime add table public.messages;
